// FlexBot outfits, scenes, poses, pants, and shoes
// Ported from fix_all.js

export const OUTFITS: Record<string, string> = {
  jesus_tee: "grey oversized vintage graphic tee with a large high-contrast black-and-white photorealistic Jesus Christ face (crown of thorns, long hair) printed large on the chest, black long-sleeve shirt layered underneath with the black sleeves and forearm cuffs visible below the tee sleeves, khaki/tan baggy carpenter pants with embroidered graphic patches on both thighs and small safety pin details, white Nike Air Force 1 Low (clean), brown leopard-print belt visible at waist, thick gold Cuban link chain, gold watch on wrist",
  chrome_tee: "black oversized heavyweight tee with a small ornate Chrome Hearts gothic cross-and-dagger cemetery cross circle logo on the left chest (white print), dark indigo heavily-baggy straight-leg jeans stacked thick at the ankle, grey and cream New Balance 550 sneakers, a brown/yellow/white batik or patterned bucket hat worn tilted slightly to the side, thick diamond-encrusted Cuban link chain with large cross pendant, iced-out AP Royal Oak watch on wrist, multiple gold rings on fingers",
  hellstar_red: "white heavily-distressed vintage-wash graphic tee with a large faded cracked Hellstar Studios sun-skull face print on the chest, bright red stacked sweatpants with bold metallic gold flame graphics and gothic script text printed running the full length of both outer legs from hip to ankle, red ribbed knit beanie hat pulled low almost to the eyebrows, white Nike Dunk Low sneakers, thick gold rope chain with large diamond pendant, gold watch",
  fur_flex: "oversized jet-black long fur coat (thick luxurious fur, hanging open), completely bare tattooed chest visible with intricate full-chest tattoo design, exposed muscular torso, massive iced-out diamond Cuban link chain hanging to the waist with large dangling diamond pendant catching light, dark baggy designer pants, black loafers, visible diamond rings on fingers",
  jordan_fit: "bright royal blue vintage Air Jordan graphic tee (iconic Jumpman logo centered on chest), medium-length denim shorts (light indigo wash), tan/caramel leather fingerless driving gloves on both hands, bright white and red Air Jordan 4 Retro Red Cement sneakers (crisp condition), thick gold Cuban chain, gold watch on wrist, athletic confident stance",
  tracksuit_fit: "grey oversized adidas-style track suit (loose fit matching jacket and pants with side stripe details), hot pink ribbed knit beanie hat, thick iced-out diamond Cuban link chain hanging, iced AP Royal Oak watch catching light prominently on wrist, dark clean sneakers, relaxed powerful posture",
  lv_monogram: "Louis Vuitton monogram brown canvas all-over print button-up shirt worn open or partially buttoned, dark designer jeans or tailored pants, large LV Monogram leather belt with prominent gold LV buckle, thick diamond Cuban link chain with cross pendant, iced-out luxury watch, sophisticated styling, fresh groomed appearance",
  mcm_boss: "oversized MCM vintage monogram brown and tan canvas jacket with large repeating MCM logos, matching or coordinating MCM brown canvas backpack worn on back, dark fitted designer jeans, worn with authority and swagger, thick gold chain, high-end watch, masculine confident expression",
  all_black: "all black outfit — black oversized graphic hoodie (heavyweight material) with subtle design details, black cargo pants with multiple pockets and strap details, brand-new all black Timberland boots (6-inch classic style, pristine condition), black watch band, minimal jewelry, striking silhouette against background",
  cactus_jack: "oversized Travis Scott Cactus Jack burnt orange and brown color-block hoodie or sweatshirt with distressed graphics and text, matching brown sweatpants with orange side stripe and Cactus Jack branding, Travis Scott x Air Jordan 1 Low Reverse Mocha sneakers or similar JS1 with backwards swoosh design, visible iced chain, confident pose",
  fog_essentials: "Fear of God Essentials taupe/greige oversized hoodie and matching oversized sweatpants in a matching neutral tone (relaxed minimalist silhouette), fresh condition, New Balance 990 v6 sneakers in grey or neutral tone, minimal accessories, clean understated luxury aesthetic, comfortable confident posture",
  gucci_suit: "Gucci GG monogram print brown and tan oversized track jacket or bomber with repeating pattern, coordinating Gucci track pants in neutral tone, Gucci Ace sneakers (white leather with green/red stripe), thick gold chain with cross, iced watch, styled luxury streetwear",
  versace_shirt: "Versace baroque gold pattern silk-look dress shirt (bright gold and black repeating Medusa face pattern) worn open over bare chest showing off tattoos, dark designer jeans or tailored pants, gold Medusa head chain pendant (large and prominent), luxury watch, dark loafers, suave confident expression",
  givenchy_fit: "Givenchy black oversized graphic tee with massive Rottweiler dog head print across full chest, heavily baggy straight-leg dark indigo jeans stacked at ankle, thick diamond-encrusted gold Cuban chain, iced-out watch, sleek minimal aesthetic, strong intimidating presence",
  dior_casual: "grey Dior Oblique monogram pattern zip-up hoodie (all-over subtle diagonal print), matching or neutral Dior track pants, New Balance 990 v6 or similar in neutral grey, minimal jewelry except watch, fresh clean luxury casual aesthetic",
  corteiz_fit: "mint green CRTZ Corteiz oversized hoodie or sweatshirt, matching or complementary flared sweatpants in mint or white, Air Jordan 1 Chicago (red, white, and black colorway), visible gold chain, youthful energetic streetwear aesthetic, confident posture",
  amiri_fit: "white oversized graphic tee with Amiri branding or subtle design, signature Amiri MX1 jeans in bone/tan with bone-stripe design running down outer seams (premium denim), Chelsea boots in tan or brown leather, AP watch prominently displayed, minimalist luxury street aesthetic",
  bape_fit: "A Bathing Ape shark camo hoodie (classic pattern) in grey/white/black, half-zipped showing layered shirt underneath, matching Bape shark camo cargo pants in coordinating colorway, Bape Sta sneakers (white with camo accents), iced chain, bold iconic hype beast aesthetic",
  supreme_fit: "red Supreme box logo hoodie (classic iconic design) with centered white box logo, black oversized sweatpants, white and red Air Jordan 1 Chicago Bred colorway, fresh clean condition, visible gold chain, confident iconic styling",
  sp5der_fit: "hot pink or bright hot pink SP5DER web hoodie with oversized white web print pattern on chest and back, black tight sweatpants for contrast, Air Max 95 in neutral or complementary color, visible jewelry, youthful energetic bold aesthetic",
  gallery_fit: "Gallery Dept. paint splatter flare jeans with realistic multi-color paint drips and splatter design across legs, vintage distressed graphic tee in neutral tone, SB Dunk Low sneakers in complementary color (often pastel or earth tone), creative artistic styling, sophisticated casual presence",
  vlone_fit: "black oversized Vlone graphic tee with large orange 'V' design printed on back (iconic Vlone logo), slim dark indigo jeans (stacked at ankle), white Air Force 1 Low sneakers, thick gold chain, minimalist bold aesthetic, confident street presence",
  trapstar_set: "Trapstar Irongate windbreaker jacket and matching windbreaker pants set (dark colors with metallic accents), New Balance 550 sneakers (classic grey/white/cream colorway), thick iced diamond Cuban link chain, fresh athletic luxury appearance, powerful relaxed posture",
  palm_fit: "Palm Angels black oversized track suit jacket and matching track pants with iconic white vertical stripe running down both outer sides, white Nike Air Force 1 sneakers, Cuban link chain, minimalist luxury aesthetic, confident athletic styling",
  off_white_fit: "Off-White diagonal stripe oversized hoodie or sweatshirt in black and white, orange-tag cargo pants (iconic Virgil design with orange security tag details), Off-White labeled sneakers or Jordan collaboration, visible gold jewelry, premium luxury aesthetic, distinctive recognizable styling",
  tech_streetwear: "Black tech-fabric jacket with neon accent trim (electric blue or magenta), dark slim-fit cargo pants with hidden pockets and utility straps, high-tech sneakers with light-up elements, sleek minimal chain, cyber-futuristic aesthetic",
  casual_luxury: "Oversized cream cashmere sweater with subtle luxury branding, tailored navy dress pants, pristine white leather low-top sneakers, simple gold watch, effortlessly refined sophisticated look",
  athleisure_premium: "Premium grey athletic set - form-fitting long-sleeve shirt and matching joggers, white Air Max sneakers, minimal jewelry, sporty yet luxurious clean aesthetic",
  streetwear_mixed: "Vintage band graphic tee tucked into black tailored trousers, oversized denim jacket with vintage patches, chunky white sneakers, layered gold chains, contemporary street style mixed with high fashion",
  minimalist_black: "All-black monochrome fit - oversized black turtleneck, perfectly tailored black wool pants, black suede Chelsea boots, single understated gold piece, clean sophisticated elegance",
  neon_tech: "Electric cyan tech shirt with black leather jacket and neon piping, black futuristic cargo pants, glow-effect sneakers, multiple tech-inspired accessories, cyberpunk street aesthetic",
  high_fashion_casual: "Luxury designer oversized sweater in neutral tone with subtle monogram, perfectly fitting designer jeans, pristine designer white sneakers, minimal gold jewelry, high-fashion relaxed vibe",
  streetwear_premium: "Oversized premium hoodie in earth tone, tailored trousers, premium retro basketball sneakers, thick gold rope chain, balanced street and luxury aesthetic",
  tech_minimal: "Form-fitting technical black shirt with geometric patterns, slim black tech pants with zippered details, sleek minimalist black and silver sneakers, tech watch, futuristic minimal style",
  rhude_vintage: "Rhude vintage-wash motocross graphic tee with faded cracked racing eagle or American flag graphic printed large across chest, Rhude monogram cream/tan Malibu shorts or matching wide-leg track pants, classic Nike Cortez in white and red or New Balance 990 in grey, AP Royal Oak iced-out watch prominently displayed, thick diamond Cuban link chain, relaxed California-meets-street luxury aesthetic, confident unbothered stance",
  chrome_hearts_full: "Chrome Hearts jet-black oversized heavyweight tee with large ornate gothic fleur-de-lis dagger cross cemetery graphic printed on front and 'Hollywood CA' in gothic script across the entire back, matching Chrome Hearts black track pants with sterling silver gothic cross hardware buttons on both side hip seams, Chrome Hearts x Converse Chuck 70 in black with hand-embroidered gothic crosses on both sides, massive double-row diamond Cuban link chain, Chrome Hearts silver dagger rings and cross rings stacked on every finger of both hands, iced AP Royal Oak watch, California gothic luxury at peak level",
  hood_classic: "crisp clean plain white Hanes heavyweight T-shirt slightly tucked into oversized dark navy Dickies 874 work pants with a thick black leather belt featuring a large square gold buckle, box-fresh all-white Nike Air Force 1 Low (pristine condition, bright white sole), white Nike athletic crew socks just visible above the sneaker collar, flat-bill New Era fitted cap in black or team colorway worn slightly tilted, thick heavy gold Cuban link chain with round medallion pendant, gold AP watch with black rubber strap, the ultimate clean hood classic — minimal but unmistakably street",
  trapstar_puffer: "oversized black Trapstar Irongate II quilted puffer jacket with bold metallic silver reflective 'TRAPSTAR LONDON' lettering arched across the full chest, matching Trapstar black quilted track pants with silver side stripe, black Nike Air Max 95 in triple black with silver air unit visible, thick iced diamond Cuban link chain, iced AP Royal Oak watch, black fitted cap or black beanie pulled low, powerful London street energy, militant luxury streetwear",
  pelle_pelle_era: "vintage Pelle Pelle Marc Buchanan oversized black genuine leather bomber jacket with massive ornate back embroidery — large embroidered eagle with wings spread full or dragon design with metallic thread in red gold and silver filling the entire back panel, matching Pelle Pelle embroidered details on sleeves and chest, dark baggy indigo wash jeans in the wide early-2000s silhouette (extremely baggy through thigh), fresh white Nike Air Force 1 Low or Air Jordan 4 in clean condition, thick gold rope chain with large diamond-encrusted medallion pendant, diamond pinky ring, flat-bill fitted cap cocked to the side — pure hip hop golden era energy, Dipset Cam'ron era nostalgia flex at its highest",
  amiri_aviator: "Amiri black full-grain leather aviator bomber jacket with thick natural shearling lamb-wool lining visible at the oversized collar, wide cuffs, and lining edge, dark Amiri distressed MX1 black jeans with black suede knee panels and heavy ankle stacking, Amiri Skel Top Low sneakers in white with anatomical skeletal foot bones printed across the vamp, thick iced diamond Cuban link chain, AP Royal Oak watch fully iced out, single teardrop diamond earring, rocker-meets-luxury California street aesthetic at highest level",
  givenchy_belt: "Givenchy black oversized tee with full-chest Rottweiler dog graphic, Givenchy GV3 leather belt with large 4G logo buckle at waist, black slim Givenchy tailored trousers, Givenchy Paris logo sneakers or Chelsea boots, massive iced Cuban link chain, AP Royal Oak watch, diamond pinky ring, fully flexed luxury designer statement",
  dior_full: "Dior Oblique all-over monogram grey-and-black pattern button-up shirt worn open over a fitted black Dior tee, Dior black tailored trousers with Dior Oblique bee-logo leather belt, Dior B22 chunky sneakers, thick iced diamond Cuban link chain, Dior Oblique saddle bag over shoulder, iced AP watch, diamond stud earrings, head-to-toe Dior luxury designer flex",
  burberry_flex: "Burberry classic camel plaid-check oversized bomber jacket with iconic camel/black/red/white check lining visible at collar and cuffs, matching Burberry check scarf draped loose around neck, dark tailored trousers with Burberry TB monogram leather belt, tan Burberry Chelsea boots, thick diamond Cuban link chain, gold Burberry monogram signet ring, AP watch, British luxury heritage at its most flexed",
  moncler_puffer: "Moncler Maya oversized shiny quilted puffer jacket in all-black with embroidered Moncler rooster logo patch on left chest, matching Moncler black quilted joggers, black Balenciaga Triple S sneakers, black Moncler knit beanie pulled low, thick iced diamond Cuban link chain catching light dramatically on the shiny puffer surface, AP Royal Oak watch, multiple gold rings, maximum flex energy",
  fendi_flex: "Fendi FF double-F monogram brown and tan canvas oversized bomber jacket with all-over Fendi logomania print, coordinating Fendi monogram tailored trousers, Fendi FF platform sneakers in tan and brown monogram canvas, Fendi belt with large FF logo buckle, thick diamond Cuban link chain, Fendi Roma bag in hand, AP watch, iced stud earrings, Italian luxury maximalist flex at peak",
  versace_full: "Versace Medusa head baroque gold and black all-over print silk dress shirt worn half-open showing tattooed chest, Versace black Medusa logo leather belt with large gold Medusa head buckle, Versace black tailored slacks, Versace gold Medusa chain loafers, massive heavy Versace-style gold Medusa head chain hanging low on chest, gold Medusa cufflinks, AP Royal Oak iced watch, gold Medusa signet ring, pure Italian gods energy",
  balenciaga_full: "Balenciaga oversized destroyed washed grey hoodie with faded distressed 'Balenciaga Paris' logo printed large across chest, matching Balenciaga grey track pants with subtle side piping, Balenciaga Triple S sneakers in all-white with extreme triple sole, Balenciaga BB monogram canvas belt, thick iced diamond Cuban link chain, AP watch, dark tinted designer sunglasses pushed to top of head, controlled luxury chaos energy",
  lv_full_suit: "Louis Vuitton all-over LV monogram brown and tan canvas matching tailored suit jacket and trousers — full head-to-toe LV monogram suit, white dress shirt underneath with open collar showing chain, large LV Monogram leather belt with polished gold LV buckle, Louis Vuitton LV Trainer sneakers, enormous iced diamond Cuban link chain with large custom pendant, AP Royal Oak fully iced, Louis Vuitton Keepall duffle bag in hand, royalty-level luxury streetwear at its absolute peak",

  // ── Hip-Hop Nostalgia Era ──
  coogi_sweater: "Coogi Australia multicolor chunky knit sweater in the iconic Biggie-era colorway — bold repeating geometric and abstract patterns in red, gold, green, blue, and orange across the full surface, oversized relaxed fit, dark baggy Guess or Polo jeans with a thick leather Gucci belt, classic black Timberland 6-inch boots (wheat or black), thick gold rope chain with large crucifix pendant, gold nugget ring on pinky, flat-bill Kangol bucket hat or fitted cap, pure 1990s Bed-Stuy luxury street nostalgia",
  tommy_retro: "vintage 1990s Tommy Hilfiger oversized colorblock rugby or polo shirt in bold red/white/navy Tommy color blocking with large embroidered Tommy Hilfiger flag logo on chest, matching or coordinating Tommy Hilfiger baggy carpenter jeans with visible Tommy logo belt, white Air Force 1 Low or Timberland boots, thick gold chain with medallion, gold watch, flat-bill fitted cap, authentic 1990s hip-hop prep nostalgia — the era when Tommy owned the block",
  nautica_retro: "vintage 1990s Nautica competition sailing jacket in bold navy and red colorblock with large Nautica sail logo on chest and back, matching Nautica track pants or dark baggy denim, white Nike Air Max or Uptempo sneakers, thick gold rope chain, gold watch, wool-blend fitted cap or navy beanie — authentic Harlem 1990s street prep that Wu-Tang and Biggie wore on the block",
  fubu_jersey: "FUBU For Us By Us oversized jersey or velour tracksuit in black and gold with large FUBU embroidered lettering across chest and back, matching FUBU track pants with gold side stripe, fresh white Air Force 1 or Nike Uptempo, thick gold Cuban link chain with FUBU medallion, gold watch, flat-bill FUBU fitted cap — pure 1990s hip-hop Harlem founding era, the uniform of rap's golden age",
  sean_john_velour: "Sean John velour tracksuit in rich deep burgundy or royal blue — plush velour jacket with 'Sean John' embroidered in script across chest, matching velour track pants, white-on-white Nike Air Force 1 or Reebok Classic, iced Cuban link chain with large diamond pendant, AP watch, velour matching color bucket hat or fitted, early-2000s Diddy-era flex at its purest — the tracksuit that ran the club",
  rocawear_fit: "Rocawear oversized denim jacket with large ornate Rocawear embroidered patch on back (Jay-Z era Roc Nation eagle logo), matching or dark wash Rocawear baggy denim jeans with Rocawear leather belt, clean white Air Force 1 or Timberland boots, thick gold chain with Roc-a-Fella diamond pendant, gold watch, Rocawear fitted cap — 2000s Jay-Z Marcy Projects-to-Def Jam era street luxury",
  ecko_unltd: "Ecko Unltd oversized graphic hoodie or jersey featuring the iconic Ecko rhinoceros logo large on chest, matching Ecko cargo pants or dark baggy jeans with Ecko leather belt, white Air Force 1 or Jordan 4, thick gold rope chain with medallion, gold watch, Ecko fitted or snap-back cap — early 2000s Marc Ecko streetwear that dominated every mall from Compton to Queens",
  akademiks_fit: "Akademiks oversized logo hoodie or denim jacket with large embroidered Akademiks logo and number graphics, matching Akademiks baggy jeans with contrast stitching, clean white Air Force 1, thick gold chain, gold watch, flat-bill fitted — the uniform of mixtape rap, BET Hip-Hop, and block corners from 2001 to 2007",

  // ── Sports / Jersey Flex ──
  nba_throwback: "Mitchell & Ness authentic throwback NBA jersey in crisp vintage colorway — either red Chicago Bulls #23 Jordan, gold LA Lakers #8 Kobe, or green Boston Celtics #34 Pierce — genuine mesh construction with stitched numbers and name, jersey worn oversized over a long white thermal or tee with sleeves extending below, dark baggy Levi's 501 jeans or shorts, classic Air Jordan matching the team colorway, thick gold Cuban link chain, flat-bill fitted in matching team colors",
  hockey_jersey_fit: "oversized vintage NHL hockey jersey in bold colorway — Detroit Red Wings #19 Yzerman in red and white, or Philadelphia Flyers #88 Lindros in orange and black, or Pittsburgh Penguins vintage black and gold — heavy mesh authentic construction, worn baggy as a top over dark baggy jeans or Dickies, matching team colored Timberland boots or Air Force 1, thick gold Cuban link chain, fitted cap in matching team colors, gold watch, the hockey jersey fit that dominated early 2000s rap videos",
  baseball_jersey: "vintage oversized Mitchell & Ness wool flannel baseball jersey in classic style — New York Yankees pinstripes or Atlanta Braves red and blue, heavy authentic wool construction with embroidered team name and number, worn open over a white tee, dark baggy jeans with thick leather belt, clean Air Jordan 1 or New Balance 550, thick gold chain, fitted cap matching team, authentic retro sports flex",
  football_jersey: "authentic NFL throwback Mitchell & Ness jersey — either Dallas Cowboys #88 Irvin in silver and blue, or Oakland Raiders #80 Rice in silver and black, or Houston Oilers vintage powder blue — mesh construction with stitched name and number, worn over a white thermal long sleeve, baggy dark jeans, Nike Air Uptempo or matching Air Force 1, thick iced Cuban chain, fitted cap matching team colorway, diamond earring",
  boxing_champion: "full championship boxing aesthetic — ornate satin boxing robe in rich colors (all red with gold trim, or all black with diamond pattern), robe worn open over bare chest revealing tattoos, boxing shorts to match in the same satin colorway, boxing boots laced tight, thick iced Cuban link chain prominently visible over bare chest, multiple diamond rings on fingers, championship belt prop draped over shoulder or held in arms, full Mayweather-level presentation",
  varsity_letterman: "vintage wool and leather varsity letterman jacket in school colors — navy body with white leather sleeves and chenille letter patch on chest, matching contrasting stripes on cuffs and collar, dark baggy straight-leg jeans, clean white Air Force 1 Low, thick gold Cuban link chain, chenille pin letters on chest, gold watch, fitted cap — the classic American flex updated for the block",

  // ── More Luxury European ──
  bottega_veneta: "Bottega Veneta all-over intrecciato woven leather bomber or blouson jacket in tan/caramel shade — the signature BV woven leather construction visible across the entire surface, matching or coordinating wide-leg tailored trousers, Bottega Veneta Pudding leather sneakers or open-toe sandals in matching leather weave, massive iced diamond Cuban link chain, AP watch, single gold earring, quiet ultra-luxury with no visible logos — the ultimate flex for those who know",
  prada_nylon: "Prada Re-Nylon oversized black puffer jacket or bomber with distinctive Prada triangular enamel logo badge on chest, matching Prada nylon cargo pants or tailored trousers, Prada cloudbust thunder sneakers in black and silver, black Prada nylon bucket hat, thick iced diamond Cuban link chain, Prada nylon crossbody bag, AP Royal Oak watch, Italian luxury minimalism at its most understated and powerful",
  margiela_tabis: "Maison Margiela MM6 all-white oversized distressed deconstructed blazer with raw edges and exposed internal seams (Margiela signature construction), matching oversized white trousers with raw hem, Margiela Tabi split-toe boots in white leather, oversized Margiela number label patch visible on collar, minimal thin gold chain, no branding except the number label — avant-garde luxury that only those who truly know fashion will recognize",
  stone_island_fit: "Stone Island oversized heavyweight cargo jacket with the iconic removable compass rose badge patch on left sleeve in reflective fabric, stone-washed or dyed in distinctive Stone Island colorway (sage green, burnt orange, or ice blue), matching Stone Island cargo pants in same dye treatment, white New Balance 990 or clean Adidas, thick iced Cuban link chain, AP watch, utilitarian luxury that started in Italy and conquered London streetwear",
  casablanca_silk: "Casablanca Studio Paris oversized silk-feel button-up shirt in the brand's signature bold illustrated print — tropical tennis court scenes or vintage automobile illustrations in vivid colors across the full shirt surface, worn open over a matching or plain white fitted tee, tailored wide-leg cream trousers, Casablanca white court sneakers, thick iced diamond Cuban link chain, AP Royal Oak watch, sunglasses with gold frames, effortlessly rich Monaco-meets-Moroccan luxury flex",
  cp_company_goggle: "C.P. Company iconic Goggle jacket in military sage green or stone grey — the signature oversized jacket with integrated goggle lens hood system built into the collar with clear lens magnification, multiple utility pockets and chest pockets, matching C.P. Company cargo trousers, clean New Balance or Adidas sneakers, CP Company lens bag over shoulder, thick gold Cuban link chain, understated technical Italian luxury that Stone Island kids respect",
  mastermind_skull: "Mastermind Japan oversized black jacket or blazer with the brand's iconic all-over skull and crossbones pattern (small repeating skulls printed across entire fabric), matching Mastermind skull track pants, black Nike Dunk High or Rick Owens boots, Mastermind skull cap, thick iced diamond Cuban link chain, AP watch, dark tinted rectangular glasses, Japanese luxury streetwear with gothic energy that hits different than anything else",
  kenzo_tiger: "Kenzo Paris oversized tiger head graphic sweatshirt or tee — the iconic roaring tiger face printed bold and photorealistic across the full chest in orange, black, and white, dark slim-cut Kenzo tailored trousers or dark jeans, Kenzo leather sneakers, Kenzo red beanie or cap, thick iced diamond Cuban link chain, AP watch, bold French luxury animal energy",
  casablanca_tracksuit: "Casablanca Paris matching full silk tracksuit — vintage illustrated tennis or motorsport scene printed all over in vivid colors across both the zip-up top and matching wide-leg pants, white Casablanca court sneakers, thick iced diamond Cuban link chain, gold AP watch, white-framed tinted sunglasses, Casablanca logo bag in hand, Monaco-level luxury resort flex",

  // ── Streetwear Brands ──
  stussy_classic: "vintage Stussy oversized 8-ball or World Tour graphic tee with large screen-printed graphic on chest in classic Stussy style, matching Stussy nylon shorts or cargo pants, Nike Cortez or New Balance 574, Stussy bucket hat or beanie, thick gold chain with medallion, gold watch, multiple rings — the original streetwear brand from Laguna Beach, worn by every surf-skate-hip-hop crossover since 1980",
  kith_tonal: "Kith tonal matching hoodie and sweatpants set in rich caramel, cream, or cobalt blue — KITH wordmark embroidered subtly on chest of hoodie, matching jogger pants with Kith script on hip, New Balance 990 or Asics Gel-NYC in matching colorway, Kith x Nobu or Kith x Yankees fitted cap, thick iced Cuban link chain, AP watch, Kith paper shopping bag in hand — the NYC luxury streetwear brunch-to-block flex",
  bbc_ice_cream: "Billionaire Boys Club oversized astronaut-print hoodie with the BBC astronaut/planet graphic across the chest (Pharrell's brand), matching BBC logo sweatpants or shorts, Ice Cream drip sneakers or Nike Dunk in custom BBC colorway, Bape/BBC fitted cap, thick gold Cuban link chain, iced watch, playful luxury energy from the mind of Pharrell — the brand that bridged skate, rap, and high fashion before anyone else did",
  anti_social_club: "Anti Social Social Club oversized pink or white hoodie with the iconic 'Anti Social Social Club' cursive script across chest in contrasting color, simple black sweatpants or jeans, Nike Air Max or Converse in clean colorway, ASSC fitted cap, thick gold chain, AP watch, diamond earring — the internet-era drop culture hoodie that every hype collector chased",
  human_made: "Human Made by Nigo oversized graphic tee or sweatshirt with vintage Americana and cartoon animal graphics (duck, polar bear, heart), matching Human Made cargo or workwear pants, Adidas Stan Smith or Vans Old Skool, Human Made trucker hat or 5-panel cap, thick Cuban link gold chain, gold watch, clean vintage Americana luxury from the BAPE founder's post-BAPE chapter",
  aime_leon_dore: "Aime Leon Dore oversized collegiate sweatshirt or polo in muted earth tones — ALD logo subtly embroidered, ALD x New Balance 550 or 990 in matching colorway, wide-leg ALD tailored trousers or straight-fit denim, ALD baseball cap or bucket hat, thin gold chain, understated gold watch, multiple rings — the Queens NYC brand that made New Balance luxury and brought prep to the block with unmatched taste level",
  noah_fit: "Noah NYC oversized rugby or polo in classic colorblock with bold Noah cross logo on chest, dark straight-leg denim or chino, New Balance 990 or Nike Cortez, Noah box logo tee layered under open rugby, thick gold chain, understated gold watch — the skate-meets-prep New York brand with an ethos and aesthetic that represents NYC authenticity without needing to yell about it",

  // ── Full Luxury Outfit Sets ──
  hermes_fit: "Hermès Oran leather slides on bare feet or worn with dark tailored trousers, Hermès Silk twill scarf in the brand's iconic equestrian print worn tied loosely around neck or as pocket square in blazer pocket, Hermès leather Birkin bag or Kelly bag prominently displayed, Hermès H-buckle belt in tan Barenia calfskin, crisp white or blue dress shirt open at collar, dark tailored blazer or suit jacket, Hermès Arceau or Cape Cod watch in gold, ultra-minimal iced chain, the flex of someone so wealthy they only wear things with no logos",
  loro_piana: "Loro Piana ultra-luxury Storm System cashmere or vicuña wool zip-up in grey or camel — the most expensive material on earth with no visible branding, matching Loro Piana tailored trousers in same shade, Loro Piana Walk leather loafers or sneakers, subtle LP logo visible only on the zipper pull, minimal thin gold chain, Patek Philippe watch, single diamond earring — the billionaire flex that makes Gucci look cheap",
  church_gucci_suit: "tailored Gucci suit in ivory white or cream with subtle GG pattern woven into the fabric, crisp white dress shirt with ornate Gucci cufflinks, Gucci GG silk tie, Gucci patent leather Oxford shoes, large iced Cuban link chain worn outside the suit jacket, AP Royal Oak watch fully iced, diamond lapel pin, white pocket square, diamond pinky rings — the Sunday best meets rap money: church clothes that cost more than most people's rent",

  // ── Current Gen Luxury ──
  amiri_snake: "Amiri black full-grain leather moto jacket with authentic road-worn distressing, vintage hand-painted snake or eagle artwork on the back panel in detailed realistic style, dark indigo Amiri MX1 jeans with tan suede knee inserts, Amiri Chelsea boots in black, heavy iced diamond Cuban link chain, AP watch fully iced, dark tinted aviator frames, rocker-meets-trap California energy",
  gallery_full: "Gallery Dept. hand-painted oversized vintage football jersey or denim jacket covered in multiple layered paint strokes in contrasting colors, Gallery Dept. paint-splattered flare jeans with multicolor drips, worn Converse Chuck 70 with paint splatter matching the jacket, Gallery Dept. painter cap covered in paint, thin gold Cuban link chain, gold watch, rings — art-world-meets-Melrose-Avenue creativity that costs like a Basquiat",
  hellstar_full: "Hellstar Studios heavyweight oversized graphic tee with the sun-skull universe graphic on front in cracked faded rubber print, matching Hellstar black sweatpants with metallic gold flame graphics running down both legs, black Nike Dunk Low or Air Force 1, Hellstar logo cap or beanie, thick iced diamond Cuban link chain, gold AP watch — the brand that went from underground Atlanta drops to everywhere in one season",
  sp5der_full: "SP5DER hot pink or neon yellow full matching set — oversized SP5DER rhinestone web hoodie with rhinestone-studded spider web covering the full chest and back, matching SP5DER rhinestone web sweatpants, rhinestone embellishments catching every light source, black or white Nike Air Max, thick iced Cuban link chain, pink or matching tinted sunglasses, AP watch — Young Thug's brand that makes everyone in the room stop talking",
  chrome_hearts_leather: "Chrome Hearts matte black full-grain leather biker jacket with hand-hammered sterling silver gothic cross hardware on collar, chest pockets, and back yoke, matching Chrome Hearts leather pants with cross zip detailing on pockets, Chrome Hearts x Converse or black engineer boots, Chrome Hearts cross ring on every finger of both hands, massive double-row iced diamond Cuban link chain, Chrome Hearts sterling eyewear, iced AP watch — the heaviest California gothic luxury possible",
  broken_planet: "Broken Planet Market oversized acid-wash or tie-dye hoodie in earthy green or brown with large Broken Planet text and planet graphic across back, matching tie-dye sweatpants, Nike Air Max 97 or 95, layered chains — thin gold and thick iced Cuban together, AP watch, tinted micro sunglasses, multiple rings — the London-born drop brand that went from 10k Instagram followers to 100k in one week",
  corteiz_full: "Corteiz CRTZ Alcatraz oversized hoodie in forest green or all-black with the Alcatraz island logo bold on chest, matching CRTZ cargo joggers with snap pockets, Nike Air Max 95 or Air Jordan 1, CRTZ fitted cap, iced diamond Cuban link chain, gold watch, multiple rings — the London underground brand from Clench that became the biggest thing in UK streetwear without a single traditional ad",

  // ── Occasion & Lifestyle ──
  ski_moncler: "Moncler Grenoble full ski performance suit — the iconic Moncler padded ski jacket in bold red or electric blue with white Moncler logo badge, matching Moncler ski pants, Moncler ski goggles pushed up on helmet, Moncler ski boots, thick iced diamond Cuban link chain visible over jacket, AP Royal Oak on wrist, full Aspen/St. Moritz luxury ski slope energy — wearing more in ski gear than most spend on a car",
  canada_goose_fit: "Canada Goose Expedition Parka in black — the iconic ultra-heavy down parka with fur-lined hood (real coyote fur trim around face), Canada Goose patch on sleeve, heavy insulated construction, dark slim jeans tucked into Chelsea boots or Timberland premium, thick iced Cuban link chain, AP watch, diamond earring, -20 degree flex in the most premium cold weather gear money can buy",
  beach_flex: "Amiri or Palm Angels swim shorts in bold print (tropical or brand logo pattern) worn with open linen shirt or no shirt showing tattooed chest, Hermès Oran leather slides, thick iced diamond Cuban link chain prominently over bare chest, Rolex Submariner or AP Royal Oak Offshore, designer sunglasses (Dior or Louis Vuitton), Loro Piana towel over shoulder, Cuban cigar in hand — the beach flex of someone with a yacht parked offshore",
  western_luxury: "Amiri or Rhude western-inspired rhinestone-studded black denim jacket with ornate embroidered designs on back and chest, matching dark Amiri denim, custom snakeskin cowboy boots in black or tan, large rodeo belt buckle in sterling silver and diamonds, thick iced Cuban link chain, AP watch, black Stetson cowboy hat tilted at an angle, diamond rings — the hip-hop cowboy flex that Lil Nas X, Post Malone, and Travis Scott put on the map",
  racing_suit: "vintage-inspired Formula 1 racing suit aesthetic — fitted multi-color satin racing suit covered in sponsor patches (Marlboro, Shell, Goodyear-style vintage patches), racing suit worn fully zipped or open to waist tied around hips, tight white racing undershirt visible above, matching racing boots, thick iced Cuban link chain, AP watch or racing chronograph, racing helmet under arm, the Rhude/Casablanca runway-to-block motorsport flex",
  safari_luxury: "Loro Piana or Hermès safari linen suit in khaki tan — perfectly tailored open-collar safari jacket with patch pockets, matching straight-leg linen trousers, Hermès Oran leather slides or tan suede loafers, thin gold chain, Cartier Santos watch, linen Panama hat at a slight angle, single diamond earring, Hermès leather bag in hand — the billionaire safari flex worn to arrive in Kenya on a private plane",

  // ── Fresh Silhouettes ──
  polo_sport_retro: "Polo Sport Ralph Lauren vintage colorblock anorak windbreaker in the iconic red/blue/yellow color blocking with large 'POLO SPORT' lettering across chest, matching Polo Sport track pants or baggy khakis, vintage Polo Sport canvas sneakers or Nike Air Max 95, Polo bucket hat in matching colors, thick gold rope chain with RL polo player pendant, gold watch, flat-bill fitted — the 1990s Harlem Lo-Life flex that stole Ralph Lauren from the country club and gave it to the hood",
  ralph_purple_label: "Ralph Lauren Purple Label fully tailored navy chalk-stripe double-breasted blazer with peak lapels, matching Purple Label tailored trousers, white French-cuff dress shirt with gold cufflinks, Purple Label burgundy or tan Oxford shoes, thick iced Cuban link chain worn outside the blazer, AP Royal Oak watch, gold signet ring, pocket square, the old-money American luxury that costs twice as much as the regular Polo line and shows it",
  ysl_rock: "Saint Laurent Paris slim-cut black leather biker jacket with quilted matelassé pattern on front panels and silver hardware, skin-tight black stretch denim jeans in Saint Laurent's iconic slim fit, black suede Chelsea boots with stacked heel, oversized ring with large stone on index finger, thin silver chain, Saint Laurent rock-and-roll energy that made Paris the capital of luxurious rebellion",
  mcqueen_tailored: "Alexander McQueen double-breasted peak lapel suit in jet black with subtle texture weave, McQueen skull lining visible at pocket square fold, white shirt underneath, skull cufflinks, Alexander McQueen oversized white sneakers on feet, heavy iced diamond Cuban link chain, AP watch, multiple skull rings, crown ring — where tailoring meets punk menace at the highest British fashion house level",
  denim_on_denim: "premium double denim look — vintage-wash oversized Levi's trucker jacket with custom embroidery or patches on back, contrasting shade matching or different wash Levi's 501 baggy jeans, white Air Force 1 or Timberland boots, large Western belt buckle in gold, thick Cuban link gold chain, gold watch, bandana tied on wrist, flat-bill cap — the Beyoncé-at-the-Grammys Canadian tuxedo taken to the streets and given hood luxury treatment",
  vintage_sportswear: "vintage 1990s deadstock athletic set — Nike ACG or Adidas Equipment full zip windbreaker in bold primary colorblock, matching track pants with snap buttons down the legs, Nike Air Max 95 or Adidas EQT Support in matching colorway, Adidas or Nike fitted hat from the same era, thick gold rope chain, gold watch — the archival sportswear collector flex that takes dedicated knowledge of sneakers and fashion history to pull off",
};

export const PANTS: Record<string, string> = {
  amiri_mx1_bone: "Amiri MX1 jeans in bone/off-white colorway with signature tan suede paneling running down both outer legs from thigh to ankle, distressed whiskering, faded wash, slim tapered fit with subtle stacking at ankle, premium raw denim construction, iconic streetwear luxury pant",
  amiri_mx1_black: "Amiri MX1 black denim jeans with black suede leather knee panels and outer leg paneling, heavily distressed with ripped knees and faded worn patches, slim tapered cut, thick stacking at ankle over sneakers, bold aggressive luxury street aesthetic",
  gallery_dept_flare: "Gallery Dept. paint-splattered flare jeans with wide leg opening from knee down, realistic multi-color paint drips and splatter marks covering front and back, light indigo distressed wash, raw hem, vintage 1970s silhouette updated for modern streetwear, artist aesthetic",
  gallery_dept_cargo: "Gallery Dept. reconstructed cargo denim in washed black, oversized wide-leg fit with multiple utility pockets sewn on thighs, hand-painted brushstroke art details, reconstructed hems and raw edge finishing, one-of-a-kind hand-crafted feel",
  hellstar_track: "Hellstar Studios black track pants with bold metallic gold flame graphics and gothic sun-skull text running the full length of both outer legs, elasticated waistband with drawstring, ribbed ankle cuffs, heavyweight cotton blend, loud graphic streetwear energy",
  hellstar_sweat: "Hellstar Studios washed grey sweatpants with large faded cracked rubber print on left thigh showing the Hellstar sun skull graphic, relaxed baggy fit with slight taper, raw edge hem, distressed vintage wash finish, premium heavyweight fleece",
  sp5der_web_pink: "SP5DER hot pink sweatpants with oversized white rhinestone-studded spider web graphic covering the full front and both legs, elasticated ankle cuffs, matching waistband, eye-catching loud pink colorway with sparkle details under light, Young Thug brand energy",
  sp5der_web_black: "SP5DER black sweatpants with neon green spider web graphic printed large across both legs, rhinestone embellishments along web lines, baggy relaxed fit with ribbed cuffs, bold contrast between black base and electric green graphic",
  corteiz_flare: "Corteiz CRTZ wide-leg flare sweatpants in forest green with embroidered Alcatraz island logo on left thigh, slight flare from knee down, elasticated waistband, ribbed cuffs, streetwear brand energy from London, limited release feel",
  corteiz_cargo: "Corteiz CRTZ nylon cargo pants in navy or olive, multiple snap-button cargo pockets on thighs and calves, adjustable hem straps, ripstop fabric, bold CRTZ embroidery on back right pocket, utilitarian military-meets-streetwear silhouette",
  trapstar_windbreaker: "Trapstar Irongate windbreaker track pants in black with reflective silver gothic Trapstar lettering running down both outer legs, elasticated ankle cuffs with zipper, lightweight shell material, matching windbreaker jacket energy, London street brand",
  vlone_sweat: "VLONE black sweatpants with large bright orange V logo printed on back right leg, relaxed baggy fit, thick cotton fleece interior, elasticated waistband and cuffs, minimal front detail, iconic Harlem/Virgil Abloh energy",
  off_white_cargo: "Off-White black cargo pants with orange industrial zip-tie tag hanging from waistband, diagonal stripe graphic on right leg in white, multiple oversized utility pockets with industrial-style hardware, slight taper, Virgil Abloh signature design language",
  palm_angels_track: "Palm Angels black track pants with iconic double white stripes running full length of both outer legs from hip to ankle, classic athletic silhouette updated with luxury pricing, elasticated ankle cuffs, gold Palm Angels embroidery on waistband, Italian luxury streetwear",
  rick_owens_bela: "Rick Owens Bela cut dark charcoal or black heavily draped wide-leg trousers with asymmetric hem, avant-garde dropped crotch silhouette, raw edge finishing, heavyweight woven fabric, architectural shape that pools over sneakers, gothic luxury aesthetic",
  rick_owens_pods: "Rick Owens Pods cut black denim with exaggerated balloon silhouette through thigh and knee tapering dramatically to narrow ankle, oversized architectural shape, raw selvedge edges, dark distressed wash, extreme avant-garde streetwear high fashion",
  dickies_874: "Dickies 874 work pants in classic black, traditional straight-leg workwear cut with generous fit through seat and thigh, pressed front crease, durable twill fabric, slightly baggy with stacking at ankle over boots or sneakers, timeless American workwear icon styled streetwear",
  dickies_baggy: "Dickies oversized baggy carpenter pants in khaki/tan, extremely wide-leg silhouette, hammer loop on left thigh, multiple tool pockets, distressed worn patches from real use, heavy canvas fabric, skater and street culture staple with authentic workwear roots",
  carhartt_wip_ab: "Carhartt WIP AB (American Bottoms) jeans in dark stone washed indigo, slightly relaxed straight-leg fit with Carhartt duck canvas-inspired denim, subtle logo patch on back waistband, workwear heritage updated for streetwear market, durable authentic construction",
  carhartt_wip_cargo: "Carhartt WIP Lawton cargo pants in Hamilton Brown or olive, double knee panels, multiple cargo pockets, slim tapered fit, ripstop nylon fabric, branded hardware and label details, workwear utility meets clean streetwear silhouette",
  stacked_jeans_black: "heavily stacked black raw denim jeans with extreme stacking and bunching at the ankle (fabric folded 4-5 times over sneaker), very long inseam intentionally worn without hemming, slim tapered fit from thigh to dramatic stack, Japanese selvedge denim quality, street flex staple",
  stacked_jeans_indigo: "dark indigo premium stacked jeans with pronounced heavy stacking at ankle, clean minimal wash with subtle fading at stress points, slim tapered leg, worn over chunky sneakers to maximize the stacked bunching effect, clean elevated street aesthetic",
  baggy_jeans_light: "light stone-washed extremely baggy straight-leg jeans from the 1990s/2000s revival era, oversized through thigh and knee with generous wide-leg opening, authentic retro denim feel, worn low on hips with visible waistband of boxers above, classic hip-hop cultural aesthetic",
  baggy_jeans_medium: "medium blue wash super baggy jeans with wide leg, cinched with a thick belt, authentic 2000s Dipset-era silhouette, real denim weight and texture, relaxed through seat and thigh with straight leg and slight stacking at ankle, cultural nostalgia flex",
  flared_denim: "dark wash bell-bottom flare jeans with dramatic wide flare from knee down, high-waisted fit, vintage 1970s-inspired silhouette modernized with premium Japanese denim, raw hem dragging slightly on ground, paired with platform sneakers or boots",
  track_pants_chrome: "Chrome Hearts black track pants with gothic cross hardware on both side hip buttons, cross embroidery on back pockets, heavyweight cotton-poly blend, slightly relaxed fit, subtle Chrome Hearts branding in white embroidery, luxury gothic California aesthetic",
  sweats_fog: "Fear of God Essentials taupe/greige heavy fleece sweatpants with relaxed oversized silhouette, subtle rubber patch logo on back waistband, dropped crotch and wide leg tapering slightly to ribbed cuffs, ultra-premium heavyweight fleece, quiet luxury minimalist streetwear",
  denim_cargo_patchwork: "patchwork cargo jeans with mixed denim washes assembled into quilt-like patchwork across entire surface — different shades of blue, black, white, and grey denim panels stitched together, cargo pockets, extreme wide-leg, handcrafted DIY aesthetic elevated to fashion art",
  trapper_flare_camo: "camo print flare trousers in olive/black/tan military camo pattern with wide leg from knee down, elasticated waistband, slightly cropped rise, military surplus aesthetic remixed into streetwear with flared silhouette, worn over chunky boots",
  waxed_black_jeans: "waxed coated black slim jeans with high-shine lacquer finish giving leather-like appearance, strong structure and stiffness from wax coating, tapered fit with slight stacking, modern rock-meets-streetwear edge, paired with black boots for maximum effect",
  lv_monogram_pants: "Louis Vuitton monogram canvas-print tailored trousers with all-over LV monogram pattern in brown and tan on a structured fabric, straight-leg cut, pressed crease, gold LV hardware at waistband, luxury street flex at highest price point",
  velour_tracksuit_pants: "deep burgundy or royal blue velour track pants with white side stripe, throwback early 2000s hip-hop aesthetic (Cam'ron era), slightly wide-leg fit, velour texture catching light, elasticated waistband, worn with matching velour jacket or contrasting oversized top",
};

export const SHOES: Record<string, string> = {
  jordan_1_chicago: "Air Jordan 1 Retro High OG Chicago in the iconic 1985 colorway — white leather upper with bold red leather overlays on toe, ankle, and eyestay, black leather collar and Nike swoosh, white midsole, red outsole, aged yellowed yellowing on midsole, crisp unworn condition, the most legendary sneaker of all time",
  jordan_1_bred: "Air Jordan 1 Retro High OG Bred in classic black and red — full black tumbled leather upper with bright red leather overlays, black Nike swoosh, white mid-sole, red outsole, clean contrast between black and red, heritage colorway tied to Michael Jordan's early Nike era",
  jordan_4_black_cat: "Air Jordan 4 Retro Black Cat in all-matte-black colorway — black nubuck upper with black plastic lace wings and support hardware, black mesh on quarter panels, black midsole with black air unit, black outsole, completely blacked-out stealthy colorway, fan-favorite since 2006 release",
  jordan_4_white_cement: "Air Jordan 4 Retro White Cement in the classic 1989 colorway — white full-grain leather upper with cement grey speckled print overlay, red Jumpman lace wings, clear sole with visible Air unit, fire red accents, grey outsole, cement speckled midsole, one of the most iconic Jordan 4 colorways",
  jordan_11_concord: "Air Jordan 11 Retro Concord in the legendary 1995/2011 colorway — white ballistic mesh and patent leather upper with concord purple suede heel and eyelets, chrome Jumpman on side, translucent icy-blue outsole, concord purple outsole pods, pristine clean condition, among the most coveted Jordan 11s",
  jordan_11_bred: "Air Jordan 11 Retro Bred in black and red — full black patent leather mudguard and overlays, white ballistic mesh upper, red Jumpman emblem on side, bred red outsole, translucent icy bottom visible, clean classic colorway from the 1996 NBA Finals, timeless premium construction",
  jordan_3_white_cement: "Air Jordan 3 Retro White Cement in the OG 1988 colorway — white full-grain leather upper with cement grey speckled print on the collar and heel tab, fire red accents, visible clear air bubble in heel, grey outsole with cement speckled midsole, iconic elephant print accents, first Jordan designed by Tinker Hatfield",
  jordan_5_grape: "Air Jordan 5 Retro Grape in the iconic 1990 colorway — white mesh upper with grey suede toe cap and heel, purple lace toggle, grape purple midsole and outsole, translucent icy outsole with herringbone traction, reflective tongue with '23' embroidered, bold 90s color blocking",
  jordan_6_infrared: "Air Jordan 6 Retro Infrared in the original 1991 colorway — white nubuck leather upper with infrared pink tongue pull loop and accents, black midsole, infrared pink outsole, heel pull loop in matching infrared, clean classic Michael Jordan championship shoe silhouette",
  jordan_12_flu_game: "Air Jordan 12 Retro Flu Game in black and varsity red — black tumbled leather upper with gold eyelets and gold Jumpman on tongue, varsity red suede toe box and heel, white midsole, black carbon fiber shank plate visible on outsole, worn by MJ during the 1997 NBA Finals while ill",
  jordan_13_he_got_game: "Air Jordan 13 Retro He Got Game in white and black — white full-grain leather upper with black pebbled leather detail panels, black toe, black outsole, holographic Jumpman on the side puck, premium suede heel lining, clean two-tone colorway inspired by the Spike Lee film",
  af1_white: "Nike Air Force 1 Low '07 in triple white — all white tumbled leather upper with perforated toe box, white midsole, white outsole, full-length Air unit, clean classic silhouette that pairs with any outfit, the ultimate clean white sneaker icon since 1982, crisp box-fresh condition",
  dunk_low_panda: "Nike Dunk Low Panda in white and black — white leather base with black leather overlays on toe, swoosh, and heel, white midsole, black outsole, clean bold two-tone colorway, padded collar, Nike branding on tongue, one of the most popular Nike Dunk releases of the 2020s era",
  air_max_95_og: "Nike Air Max 95 OG in the original neon yellow colorway — dark grey mesh base with layered black and dark grey suede overlays mimicking muscle and body anatomy design, neon yellow Swoosh and sole accents, full-length visible Air unit, technical 1995 design language ahead of its time",
  air_max_97_silver_bullet: "Nike Air Max 97 Silver Bullet in metallic silver — full metallic silver reflective upper with 360-degree Air Max unit visible in full-length sole, silver laces, Italian flag colors on tongue (red and green stripes), reflective silver paint catches all light, futuristic bullet-train inspired design",
  yeezy_350_v2_zebra: "Adidas Yeezy Boost 350 V2 Zebra in white and black — full Primeknit upper in white with black zigzag stripe pattern running horizontally across the shoe, SPLY-350 text woven into side stripe, full-length Boost foam midsole in white, semi-translucent white rubber outsole, Kanye West design icon",
  yeezy_700_wave_runner: "Adidas Yeezy Boost 700 Wave Runner in multi-color — grey suede and mesh upper with red, blue, black, and white leather overlays in chunky dad-shoe silhouette, Boost foam midsole, chunky thick outsole in grey and navy, bold thick heel counter, the original Yeezy dad shoe that started a trend",
  nb_550_white_grey: "New Balance 550 in white and grey — clean white leather upper with grey leather heel and N logo overlay, retro basketball shoe silhouette inspired by 1989 NB basketball line, low-top profile, gum/white sole, simple minimal design that became a staple for streetwear and prep aesthetics",
  nb_990v6: "New Balance 990v6 in premium grey — full premium pigskin suede and mesh upper in classic grey colorway, ENCAP midsole technology with grey foam and EVA layer, durable rubber outsole, Made in USA heritage construction, understated premium quality, no-logo-needed design confidence",
  balenciaga_triple_s: "Balenciaga Triple S in white and grey — extreme triple-sole construction stacking three separate midsole layers (mesh, EVA, rubber) for maximum platform height, white and grey color blocking, exaggerated chunky silhouette that defined the ugly-sneaker luxury trend, heavy large-format Balenciaga branding",
  alexander_mcqueen_oversized: "Alexander McQueen Oversized Sneaker in white — pristine all-white leather upper with clean minimal design, exaggerated thick platform rubber sole in white, elongated silhouette, McQueen embossed on the heel counter, premium Italian leather construction, clean luxury white chunky sneaker that elevated the platform sneaker category",
  lv_trainer: "Louis Vuitton LV Trainer in monogram brown and tan — full-grain LV monogram canvas upper with white leather overlays and heel counter, white rubber midsole, gum rubber outsole, LV embossed on tongue, brown laces, premium luxury construction at highest price point, flex-worthy designer sneaker",
  dior_b22: "Dior B22 sneaker in white and blue — white technical mesh and suede upper with reflective grey and royal blue panels, CD Diamond Oblique canvas overlays, chunky layered midsole construction, Dior Paris branding on tongue and heel, bold luxury dad-shoe silhouette, French luxury house sneaker statement",
  rick_owens_ramones: "Rick Owens Ramones low-top in black — full premium black leather upper with elongated square toe, thick crepe midsole and outsole in off-white or black, clean architectural minimalist design with zero branding except subtle heel tag, avant-garde gothic aesthetic, favored by fashion insiders worldwide",
  amiri_skel_top: "Amiri Skel Top Low in white — white leather upper with exposed anatomical skeleton foot bones printed across the vamp in black graphic, contrast outsole, premium California luxury brand design language, Amiri star logo on tongue, edgy luxury street aesthetic combining fashion and body art motifs",
  bape_sta_white: "A Bathing Ape Bape Sta in white — white leather upper with iconic Bape shooting star logo replacing the Swoosh on the side (five-pointed star with motion streaks), clean white midsole and outsole, patent leather toe detail, Japanese streetwear icon that predates many modern collaborations, bold collector piece",
  off_white_aj1: "Off-White x Air Jordan 1 Retro High in the Chicago colorway — standard AJ1 Chicago base construction with Virgil Abloh deconstructed design elements: exposed foam tongue, left shoe only half-Swoosh, zip-tie hangtag on lace, Off-White text on midsole in Helvetica, orange and black Off-White box branding, the most iconic sneaker collaboration of the 2010s era",
  travis_scott_aj1_low_mocha: "Travis Scott x Air Jordan 1 Low Reverse Mocha — light British tan suede upper with reverse swoosh pointing backward instead of forward (Travis signature design element), mocha brown overlays, sail white midsole, brown outsole, Cactus Jack branding on tongue, loose deconstructed feel, premium collaboration with suede materials throughout",
  chrome_hearts_converse: "Chrome Hearts x Converse Chuck Taylor All Star — classic white canvas Chuck upper with Chrome Hearts gothic cross embroideries on both sides and toe box in black thread, Chrome Hearts silver cross charm on lace, standard Converse vulcanized sole in white, hand-embroidered details making each pair slightly unique, underground luxury meets American heritage",
  gucci_ace: "Gucci Ace Sneaker in white leather — clean white leather upper with iconic green and red web stripe running across the toe box (the distinctive Gucci stripe), interlocking GG metal logo on ankle, Gucci embossed on white midsole, vintage rubber outsole, Italian luxury house sneaker that mixes athletic and formal aesthetics",
};

export const SCENES: Record<string, { scene: string; light: string }> = {
  kitchen_white: {
    scene: "white gloss cabinets, dark marble countertop, kitchen island with stools, hanging pendant lights",
    light: "bright natural window light mixing with warm overhead kitchen lights, soft shadows on marble",
  },
  kitchen_oak: {
    scene: "warm honey oak wood cabinets, granite countertop, bottle of Hennessy with glass, blunt in glass ashtray, stove and fridge visible",
    light: "warm golden hour sunlight streaming through window, creating amber glow on wood grain",
  },
  penthouse: {
    scene: "marble floors, sheer floor-to-ceiling curtains, Miami or Dubai luxury penthouse interior, modern furniture, city view through windows",
    light: "soft diffused natural light from floor-to-ceiling windows, warm golden hour sunset",
  },
  gas_station: {
    scene: "Chevron gas station at dusk, pump 6 visible, white Porsche Cayenne parked prominently nearby, bright fluorescent pump lights",
    light: "golden hour dusk lighting mixed with bright artificial pump and station lights, dramatic contrast",
  },
  vegas_rooftop: {
    scene: "Bellagio fountains shooting water far below, Las Vegas Strip sprawling out at dusk with neon lights, rooftop terrace with Hennessy bottle and table setup",
    light: "dusk twilight blue hour lighting, neon Vegas lights beginning to glow in background, warm table lighting",
  },
  dubai_rooftop: {
    scene: "Burj Khalifa skyline visible in distance, Dubai cityscape at night, modern luxury rooftop terrace, table with MCM backpack, pistol, money, and bottles",
    light: "nighttime city lights reflecting, warm ambient terrace lighting, dramatic skyline glow",
  },
  rolls_driveway: {
    scene: "matte black Rolls-Royce Cullinan in driveway, luxury estate with brick pavers, stone pillars, manicured landscaping, dusk lighting",
    light: "warm golden hour sunlight catching on car paint, ambient estate lighting beginning to glow",
  },
  rolls_phantom: {
    scene: "matte black Rolls-Royce Phantom in grand driveway, tall white columns, palm trees, luxury estate setting, elegant minimalist background",
    light: "warm golden hour sunset light, soft romantic lighting on car and columns",
  },
  private_jet: {
    scene: "private jet interior cabin, cream quilted leather seats, porthole window with sky/clouds visible, Louis Vuitton luggage, luxury cabin appointments",
    light: "warm diffused cabin lighting, natural light from porthole window creating ambient glow",
  },
  jet_tarmac: {
    scene: "Gulfstream or similar large private jet on airport tarmac, cabin stairs deployed, luxury SUV parked nearby, open sky background",
    light: "bright daylight, clear sunny day lighting, dramatic shadows from jet and stairs",
  },
  yacht_deck: {
    scene: "superyacht deck with polished white surfaces, luxury wet bar, open ocean stretching to horizon, Miami or tropical coastline visible, modern yacht appointments",
    light: "bright natural sunlight, sparkling reflections off ocean and polished surfaces",
  },
  casino_vip: {
    scene: "VIP casino table with green felt, stacked black and red $100 chips towers, casino cards, crystal chandelier above, cigars, cocktails, professional lighting",
    light: "warm golden casino lighting, spot lights on table, ambient dramatic casino atmosphere",
  },
  nightclub_vip: {
    scene: "nightclub VIP booth, sparkler bottles with flames shooting up, neon and strobe lights flashing, velvet booth seating, crowd visible below on dance floor",
    light: "dramatic neon lights, strobes, gold sparkler flames, nightclub atmosphere lighting",
  },
  mansion_pool: {
    scene: "infinity pool with crystal turquoise water, mansion deck, palm trees, poolside luxury furniture, Hennessy bottle on pool table, golden hour beachfront setting",
    light: "warm golden hour sunset, sparkling water reflections, ambient pool lighting",
  },
  ferrari_garage: {
    scene: "luxury car garage with 4 exotic sports cars (Ferrari, Lamborghini, etc.) spotlit on polished epoxy floors, high ceilings, professional gallery-like presentation",
    light: "professional spotlights on each car, polished epoxy reflecting lights, gallery-quality dramatic lighting",
  },
  hotel_lobby: {
    scene: "5-star marble lobby with soaring ceilings, crystal chandelier, white marble floors, premium furniture, Louis Vuitton luggage prominently displayed",
    light: "warm ambient hotel lobby lighting, chandelier casting elegant patterns",
  },
  miami_beach: {
    scene: "South Beach Miami golden hour, art deco hotels visible in background, Bentley parked at curb, sandy beach, warm ocean atmosphere",
    light: "warm golden hour sunset lighting, orange and pink sky, reflecting off beach sand",
  },
  penthouse_balcony: {
    scene: "penthouse high-rise balcony at night, city lights sprawling far below, table with Hennessy bottle, glass, cigar, cash, dramatic urban nightscape",
    light: "nighttime city lights below, warm ambient balcony lighting, dramatic urban contrast",
  },
  barbershop: {
    scene: "upscale barbershop, black leather barber chair, ring light above, white or neutral walls, large ornate mirror, professional barbering setup",
    light: "bright ring light creating professional illumination, warm ambient shop lighting",
  },
  walk_in_closet: {
    scene: "luxury walk-in closet with hundreds of sneaker shoe boxes stacked, full clothing racks with designer pieces, large wall mirrors, organized luxury display",
    light: "bright natural and ambient closet lighting, illuminating all the shoe boxes and clothes",
  },
  parking_lot: {
    scene: "parking lot at dusk, matte black Lamborghini Urus SUV parked prominently, dusk city skyline in background, urban street setting",
    light: "dusk twilight lighting, city lights beginning to glow, warm ambient outdoor lighting",
  },
  city_street: {
    scene: "urban city street with red Corvette sports car parked at curb, sidewalk, scattered autumn leaves, tall buildings, classic American muscle car aesthetic",
    light: "warm golden hour autumn light, seasonal atmospheric lighting, dramatic street shadows",
  },
  basketball_court: {
    scene: "urban blacktop basketball court, chain-link fence, golden hour sunlight, street court atmosphere, ghetto fabulous setting",
    light: "warm golden hour sun creating long dramatic shadows across the court",
  },
  office_boardroom: {
    scene: "modern glass office boardroom, sleek white marble table, floor-to-ceiling windows, city skyline visible, minimalist luxury decor",
    light: "natural daylight from windows mixed with warm office lighting, professional clean lighting",
  },
  gym_interior: {
    scene: "upscale gym interior, mirrored walls, dumbbells and weights visible, modern gym equipment, polished floors, professional fitness environment",
    light: "bright overhead gym lights with reflections in mirrors, sharp clear lighting",
  },
  coffee_shop: {
    scene: "trendy modern coffee shop, exposed brick walls, wooden tables, vintage coffee machines visible, cozy urban cafe atmosphere",
    light: "warm ambient cafe lighting with natural window light, cozy warm glow",
  },
  apartment_bedroom: {
    scene: "luxury apartment bedroom, king-size bed with premium bedding, floor-to-ceiling windows, city view, minimalist decor, soft ambient lighting",
    light: "soft warm bedroom lighting with natural light from windows, romantic ambient atmosphere",
  },
  street_walk: {
    scene: "busy city street, pedestrians walking, storefront windows, urban street scene, daytime foot traffic, urban energy",
    light: "bright daylight with natural shadows, urban street lighting, natural sunlight",
  },
  shopping_mall: {
    scene: "upscale shopping mall interior, designer store fronts, polished floors, mall ambiance, luxury retail environment",
    light: "bright mall lighting with warm accent lights, professional retail lighting",
  },
  home_office: {
    scene: "modern home office, standing desk, computer setup, bookshelf, window with city view, tech-forward professional space",
    light: "natural window light with desk lamp, professional home office lighting",
  },
  nighttime_street: {
    scene: "nighttime city street with neon signs, street lights, urban nightlife atmosphere, people walking, vibrant night energy",
    light: "neon street lights, artificial night lighting, colored neon signs reflecting",
  },
  lambo_street: {
    scene: "downtown city street at night, bright orange Lamborghini Huracán Evo parked at curb with both scissor doors open, neon storefront signs and streetlights reflecting in wet rain-slicked pavement, glass skyscrapers towering on both sides, other luxury cars visible further down the block",
    light: "nighttime city streetlights and multicolor neon reflections on wet pavement, orange Lamborghini paint catching all ambient light dramatically, deep shadows between skyscrapers",
  },
  hellcat_block: {
    scene: "urban city block at dusk, Dodge Challenger SRT Hellcat in Hellraisin purple with factory widebody kit on 22-inch custom wheels sitting at the curb, brick rowhouse homes and corner bodega with neon open sign behind, fire hydrant at the curb, autumn leaves scattered on sidewalk, iron fence details",
    light: "golden dusk light catching on the purple metallic paint and chrome wheels, warm streetlights flickering on, dramatic twilight atmosphere blending orange sky with urban street lighting",
  },
  slab_houston: {
    scene: "Houston Texas Third Ward block at night, 1994 Chevrolet Caprice Box fully built slab rolling on 30-spoke Cragar swanga elbow wheels protruding wide beyond the tires, deep candy apple red paint gleaming under nighttime street lights, trunk cracked open showing fifth wheel setup, Houston skyline and palm trees in background, slow-rolling posted energy",
    light: "nighttime Houston street lights and neon signs, candy paint shifting color and gleaming under amber artificial light, dramatic glow on chrome swangas and wet asphalt",
  },
  atlanta_trap: {
    scene: "Atlanta Georgia street at dusk, jet black Dodge Charger Hellcat on chrome Forgiato wheels parked aggressively in front of a worn brick rowhouse, iron security gate on door, weathered oak trees with hanging moss, red Georgia clay visible in driveway cracks, faint Atlanta skyline in distance",
    light: "late golden hour fading rapidly to dusk, warm orange Atlanta sky behind, streetlights turning on over the Charger, dramatic contrast between warm sky glow and cool street shadows",
  },
  benz_lot: {
    scene: "private luxury car lot at night, four blacked-out Mercedes-AMG vehicles lined up — G63 Wagon, S63 Coupe, GLE 63, and C63 — all matte or gloss black with prominent AMG badging, polished concrete floor under professional spotlights, fleet representing pure power and wealth",
    light: "dramatic professional spotlights illuminating each AMG from above, polished surfaces reflecting light, pitch black night sky beyond the lit perimeter, showroom-quality dramatic lighting",
  },
  chicago_block: {
    scene: "Chicago South Side block in winter, grey overcast sky, light snow dusting the sidewalk and parked cars, black Chevrolet Suburban sitting tall on 26-inch chrome floater wheels at the curb, Chicago brick two-flat buildings lining both sides, corner bodega glowing warm from inside, elevated L-train tracks cutting above the street in background",
    light: "cold grey overcast winter daylight, warm orange artificial streetlights glowing against the grey sky, warm bodega window light spilling onto snowy sidewalk, harsh cold urban winter atmosphere",
  },
  mansion_driveway: {
    scene: "massive circular estate driveway with brick pavers, pearl white Rolls-Royce Phantom Extended Wheelbase and matte white Bentley Bentayga parked side by side, large stone water fountain at center of circular drive with running water, symmetrically manicured boxwood hedges flanking both cars, grand white columned mansion facade behind",
    light: "warm golden hour sunset light bathing the entire estate, long dramatic shadows from hedges and columns, embedded driveway lighting illuminating both cars from below, ultimate wealth backdrop",
  },
};

export const POSES: Record<string, string> = {
  kitchen_blunt: "POSE: Standing in kitchen, lighting a blunt with lighter, thick white smoke curling from the tip, head tilted back slightly with relaxed expression, lean cup in other hand, casual dominance, full body visible, candid photo feel",
  kitchen_lighter: "POSE: Standing at counter, lighting blunt with Bic lighter, orange ember glow visible at the tip, smoke wisping up, counter clutter behind (bottles, cups, ashtray), confident relaxed expression, full body visible, candid street photo",
  kitchen_gun: "POSE: Standing in kitchen, pistol aimed directly at camera with both hands on grip, serious cold stare, lean cup in other hand, counter visible behind, intimidating presence, full body visible, raw candid shot",
  kitchen_ak: "POSE: Standing in kitchen, AK-47 raised at 45-degree angle, Jack Daniels bottle tucked under other arm, grinning expression, counter backdrop, full body visible head to sneakers, real candid photo",
  kitchen_dual: "POSE: Standing in kitchen, massive cash brick in one raised hand, AK-47 in other raised hand, both weapons/wealth raised high, triumphant laughing expression, full body visible, candid flash photography",
  counter_sit: "POSE: Sitting on kitchen counter between fridge and stove, holding massive cash brick stack pressed up to chin like making a phone call, cigar smoke curling, relaxed confident smile, full body visible, candid interior photo",
  floor_lay: "POSE: Laying on side on kitchen floor, one arm wrapped around and hugging massive rubber-banded cash brick, eyes looking directly at camera, relaxed powerful expression, full body visible, raw street photo",
  arms_spread: "POSE: Standing with both arms spread wide out to sides showing wingspan, 8-10 massive rubber-banded cash brick stacks held from wrist to shoulder on both arms like weights, pure wealth flex, laughing expression, full body visible, candid photo",
  floor_surround: "POSE: Sitting cross-legged on kitchen floor completely surrounded by scattered cash bricks and loose money piled on all sides around the body, cash buried, dominant unbothered expression, full body visible, raw candid shot",
  car_hood_lay: "POSE: Laying chest-down on the hood of a white Rolls-Royce, both arms hugging and pressing a massive cash brick stack to chest, peaceful expression, head turned toward camera, full body visible on hood, candid outdoor photo",
  car_hood_sit: "POSE: Sitting on Rolls-Royce hood, holding a massive cash brick stack pressed tight to face like holding a phone, Jack Daniels bottle on hood nearby, relaxed smirk, full body visible, candid driveway photo",
  car_lean: "POSE: Leaning against Rolls-Royce car body, lit blunt in mouth with thick smoke curling, crossed arms, cold focused expression, full body visible, candid street photo",
  low_crouch: "POSE: In a street squat position, forearms resting on knees, massive rubber-banded cash brick stack dangling from one hand, serious street expression, full body visible, real candid photo",
  jet_seat: "POSE: Sitting reclined deep in plush cream leather private jet seat, back sunk into seat, legs crossed at knee, one arm draped over armrest with diamond watch glinting, other hand holding crystal glass of Hennessy cognac with ice slightly raised, satisfied smirk, porthole window with clouds visible, full upper body visible, candid photo",
  jet_lean: "POSE: Standing in private jet aisle, one hand gripping overhead luggage rack, body leaning back against cockpit divider wall, other hand holding rubber-banded cash brick raised to chest level, completely relaxed expression, gold chain and AP watch catching cabin light, Louis Vuitton bag visible near feet, full body visible, candid photo",
  casino_table: "POSE: Seated at VIP casino poker table, leaning forward with both forearms on green felt, massive tower of black $100 chips stacked in front, right hand holding fan of casino cards, left hand holding lit cigar with realistic smoke, gold Cuban link hanging forward, AP watch clearly visible, cold confident expression, crystal cocktail glass on table, full upper body visible, candid photo",
  yacht_bow: "POSE: Standing at very front bow of yacht, both arms stretched wide open gripping chrome steel rails on both sides, body leaning slightly back with total confidence, legs planted apart, wind visibly moving clothing and hair back, smiling or laughing looking at camera, open ocean stretching infinitely behind, full body visible, candid outdoor shot",
  table_spread: "POSE: Sitting at table completely covered in overwhelming display of wealth — table buried under loose $100 bills piled everywhere, multiple rubber-banded cash bricks in towers, Hennessy bottle, crystal glass, gold Cuban link chains coiled, AP watch, diamond rings, pistol laid flat, car keys, passport scattered, both elbows on table, chin resting on interlaced fingers, looking directly at camera with slow unbothered expression, full upper body visible, candid photo",
  wrist_check: "POSE: Standing facing camera, both arms raised and bent at elbows, wrists held up toward camera side by side in wrist check display, right wrist showing iced-out AP Royal Oak watch with diamond sparkle, left wrist showing diamond tennis bracelet and thick gold Cuban bracelet, multiple diamond rings on fingers of both hands, looking down at wrists with slight smirk then back up at camera, chains hanging, shoulders slightly hunched forward to show wrists prominently, full upper body visible, candid photo",
  pocket_stuff: "POSE: Standing facing camera, both hands simultaneously stuffing or pulling fat rubber-banded cash brick stacks out of both pants pockets, both pockets fully loaded and overflowing, looking at camera with huge grin, shoulders up, total energy, multiple stacks being pushed into or pulled from pockets, full body visible, candid street photo",
  sneaker_check: "POSE: Sitting down, right leg crossed over left knee at 90 degrees, right foot kicked up and angled toward camera showing sole and bottom of extremely exclusive sneaker, both hands gripping raised ankle/shoe showing it off like trophy, looking directly at camera smirking, chains hanging with forward lean, sneaker sole fills lower-center frame, full body visible, candid photo",
  nightclub_bottle: "POSE: Standing at nightclub VIP table, right hand raised high holding Ace of Spades or Dom Perignon bottle with glowing lit sparkler shooting gold sparks upward, arm fully extended, head tilted back with huge grin looking up at sparks, left hand at waist holding rubber-banded cash brick, strobe and neon nightclub lights sweeping across, bottle service table with ice buckets behind, full body visible in dynamic energy, candid nightclub photo",
  cash_bath: "POSE: Sitting in backseat of luxury car (Rolls Royce interior with cream quilted leather seats, chrome trim), loose $100 bills covering every surface and actively falling/floating all around inside car, some sticking to person, both arms spread wide across back of seat, completely unbothered smiling, window down showing nighttime city passing outside, full body in car interior visible, candid photo",
  toss_money: "POSE: Mid-action throwing massive fistful of loose $100 bills upward into air, both hands releasing cash, bills frozen mid-flight scattered tumbling above head and around body in all directions, some bills close to camera with $100 Benjamin Franklin faces visible, head tilted back laughing with full open-mouth joy eyes up at raining bills, body in slight backward lean from force of toss, bills filling air around, full body visible, raw candid shot",
  bed_money: "POSE: Laying flat on back on bed, every inch of bed surface covered in overlapping loose $100 bills and rubber-banded cash brick stacks piled everywhere, some bills covering legs and torso, both arms behind head on pillow fingers laced, one eye slightly squinting toward camera, calm satisfied expression, camera shot from directly above looking straight down, full body buried in cash, candid photo",
  two_shot: "POSE: Two famous figures standing side by side facing camera, both clearly identifiable, one giving other firm handshake or fist dap at waist level while both look confidently into camera, both wearing distinct full outfits with visible chains, white Porsche or Rolls-Royce parked directly behind both, one figure holds rubber-banded cash stack in free hand, other holds styrofoam lean cup or bottle, both serious or smirking expressions, gas station or parking lot setting, full body of both head to sneakers, candid photo",
  pool_edge: "POSE: Sitting on edge of infinity pool, both legs dangling in turquoise water feet submerged, one hand resting on pool deck behind for support, other hand holding enormous fanned spread of $100 bills fanned wide open toward camera, looking sideways at camera, sunglasses pushed up on head, relaxed expression, infinity pool edge dropping to ocean/city view behind, full body visible, candid outdoor photo",
  balcony_fan: "POSE: Standing on balcony, fanning massive stack of $100 bills wide open like a deck of cards, cigarette smoke drifting, cool confident expression, city lights visible behind, full body visible, candid night photo",
  dual_hold: "POSE: Standing, holding both a massive cash brick and AK-47 both raised high, triumphant laugh expression, full body visible, raw candid photo",
  gun_sideways: "POSE: Standing in street environment holding a pistol sideways gangster-style aimed directly at camera with one hand, other hand at side or making hand sign, cold dead-eye stare directly into lens, slight forward lean, body angled slightly with full face and gun visible, aggressive street posture, full body visible, raw candid photo",
  double_strap: "POSE: Standing facing camera with both arms raised holding two pistols simultaneously — one in each hand raised to chest/shoulder height pointed forward or skyward, intense mean mug expression with eyes locked on camera, chest out, aggressive commanding stance, full body visible, real candid street photo",
  ak_lean: "POSE: Leaning back against a wall in a street setting, AK-47 held horizontally across chest with both hands gripping it, one foot flat on wall behind, cold stone-faced expression staring at camera, body relaxed but armed, cigarette or blunt possibly in mouth, full body visible, raw candid photo",
  gun_money: "POSE: Standing and holding pistol pointed upward in one raised hand, other hand fanning a massive thick stack of $100 bills toward camera, both items held high and proudly displayed, confident smirk or dead serious expression, city or block background, full body visible, candid street photo",
  block_squat: "POSE: Deep street squat low to the ground on the block — knees fully bent, forearms on knees, both hands throwing up hand signs toward camera, mean mug expression, posted up energy, concrete sidewalk or block setting, full body visible close to ground level, raw candid street photo",
  trap_phone: "POSE: Standing casually holding an old-school flip phone to ear in one hand like making a call, other hand resting on waist with handle of Glock clearly visible tucked in waistband with shirt pushed aside, expression focused and aware, street corner setting, full body visible, real candid photo",
  mean_mug: "POSE: Standing squarely facing camera with arms folded tight across chest, completely stone-faced intense stare directly into lens, jaw tight, shoulders broad, intimidating presence, no smile — pure dead expression, street setting background, full body visible, raw candid photo",
  money_rain: "POSE: Standing with both arms raised high throwing loose $100 bills up into the air, bills frozen mid-air all around and falling, head tilted back laughing with pure joy and energy, looking up at falling money, expression of unbothered celebration, full body visible with bills raining down, raw candid photo",
  lean_sip: "POSE: Standing at counter or table carefully pouring purplish lean syrup from small medicine bottle into a white styrofoam double cup, head tilted down focused on the pour, one eye slightly squinted in concentration, expression calm and deliberate, counter setting with cups and bottles visible, full body visible, real candid photo",
  gang_pose: "POSE: Standing facing camera with both hands simultaneously throwing up gang signs — fingers bent, twisted, and shaped in aggressive hand gesture formation held at chest or face level, expression intense and hard with mouth slightly open showing aggression, direct eye contact with camera, full body visible, raw candid street photo",
  hood_lean: "POSE: Leaning against driver-side car door of a parked car on a city block, one foot propped up on bumper or wheel well, arms crossed or one hand in pocket, smoke rising from blunt or cigarette in mouth, expression relaxed and watchful, posted-up energy like owning the block, full body visible, candid street photo",
  glock_flash: "POSE: Standing and lifting shirt up with one hand revealing a Glock pistol tucked in waistband, other hand gesturing or pointing at the revealed gun, expression confident and threatening — look directly at camera, shirt lifted just enough to show weapon clearly, full body visible, raw candid photo",
  street_corner: "POSE: Standing on a street corner with one foot propped up on a fire hydrant, bent at knee, one hand counting a thick stack of cash with bills fanned between fingers, other hand on hip or hanging at side, commanding the corner, confident street expression, city block background, full body visible, candid street photo",
  dice_roll: "POSE: Crouched low to the ground in a circle shooting dice on concrete — one hand mid-throw releasing dice onto ground, other hand holding a visible cash pile or rubber-banded stack next to the dice game, intense focused expression watching the roll, other cash piles visible on ground nearby, full body crouched visible, raw candid street photo",
  back_strap: "POSE: Walking away from camera down a street or alley, shot from behind, head turned back over one shoulder looking back at camera with serious expression, gun handle clearly visible sticking out of back waistband above the beltline, outfit fully visible from behind including shoes, candid walking-away shot, full body visible",
  waist_draw: "POSE: Standing facing camera, right hand gripping the handle of a Glock pistol in a mid-draw — gun halfway out of the front waistband, barrel just clearing the belt line, hand firmly on grip, left hand at side loose, stone-cold mean mug expression — jaw clenched, eyes dead and locked directly into the lens with zero emotion, body slightly squared and still, threat energy at maximum, full body visible, raw candid street photo",
  shirt_lift_reveal: "POSE: Standing facing camera, left hand gripping the bottom hem of shirt and lifting it to reveal a Glock pistol tucked sideways in the front waistband, right hand reaching down and gripping the exposed gun handle ready to pull, eyes looking directly at camera with total coldness and no expression, shirt lifted just enough to expose the full gun clearly, iced chain swinging slightly forward from the lean, full body visible, raw candid photo",
  double_aim: "POSE: Standing with both feet planted wide and firm, both hands gripping a single pistol in a two-handed stance aimed directly at camera — barrel pointed straight at lens, arms extended forward slightly, completely deadpan stone-cold expression with intense unblinking stare locked on camera, body squared and still, full threat energy, full body visible, raw candid photo",
  gun_face_level: "POSE: Holding a pistol up near face level in one hand, barrel tilted toward camera, other hand making a street hand sign gesture at hip level, cold calculating expression with one eyebrow slightly raised and jaw tight, direct eye contact into lens, body at slight angle, iced chain visible, menacing composed energy, full body visible, raw candid photo",
  waistband_touch: "POSE: Standing at a 3/4 angle, one hand resting casually with fingertips just touching the Glock handle tucked in front waistband — not drawing, just letting it be seen, other arm hanging at side completely relaxed, unbothered cold expression scanning slightly off-camera, expression says it's there if needed, posted-up energy, full body visible, raw candid street photo",
  gun_tuck_kneel: "POSE: One knee planted on the ground in a low street kneeling position, gun held sideways gangster-style in the front hand at chest level aimed at camera, other fist on the ground for balance, intense dead-eyed mean mug staring straight into lens, iced chain hanging forward from the forward lean, full body visible from a slightly low camera angle, raw candid photo",
  middle_finger: "POSE: Standing facing camera directly, right arm extended forward with right middle finger raised fully upright toward the lens — classic single middle finger, expression ice cold and completely emotionless staring directly at camera, other arm hanging at side or holding a cash stack, no smile, no hesitation, full body visible, raw candid photo",
  double_middle: "POSE: Standing facing camera, both arms extended forward with BOTH middle fingers raised simultaneously at the camera — full double bird, expression somewhere between laughing hard and stone cold serious, direct eye contact, pure unbothered energy of not caring about anything, full body visible, raw candid photo",
  sign_money: "POSE: Standing with one hand throwing up complex interlocked finger street signs held at chest level, other hand holding a fat fanned spread of $100 bills pushed forward toward camera, expression intense and focused with direct stare, chains hanging and catching light, energy of representing the block while showing the bag, full body visible, raw candid photo",
  peace_flex: "POSE: Standing with one hand throwing up a sideways peace sign (street style, not hippie — two fingers sideways tilted), other hand holding a rubber-banded cash brick with the stack dangling, slight lean to one side, relaxed confident smirk, unbothered energy, chains visible, full body visible, raw candid photo",
  corner_post: "POSE: Standing on a street block corner, one foot propped up on a weathered plastic milk crate, arms folded across chest with one hand gripping a fat rubber-banded cash stack dangling at hip level, flat-bill fitted cap pulled very low almost to the eyebrows, hard cold expression slowly scanning up the block, blunt pinched between lips with smoke curling upward, posted-up energy like every inch of the block is owned, city block and corner store visible behind, full body visible head to sneakers, raw candid street photo",
  trap_count: "POSE: Sitting at a trap house kitchen table, both hands actively counting and separating a massive messy pile of loose $100 bills spread across the entire table surface, cash in multiple uneven piles, several completed rubber-banded stacks already set aside, head slightly tilted down focused on the count but eyes looked up at camera with one eyebrow raised mid-count, Hennessy bottle at corner of table, two digital counting scales visible, blunt burning in ashtray, full upper body visible, raw candid photo",
  hood_watch: "POSE: Posted up against an exterior brick wall, arms hanging loosely at sides, one hand gripping a phone screen-down at hip level, other hand resting on hip with fingertips near waistband where a Glock handle is faintly visible, head turned sideways scanning up the street with sharp calculating eyes, expression alert and watchful — clocking everything, blunt smoke rising from corner of mouth, chain hanging, full body visible against the brick wall, raw candid street photo",
  flex_on_hood: "POSE: Sitting directly on the front hood of a parked car with both legs dangling off the front above the bumper, both hands simultaneously throwing up aggressive hand signs aimed directly at camera, expression wide open laughing or taunting with mouth open, multiple rubber-banded cash bricks stacked on the hood beside them, one brick balanced on knee, driver-side door open behind showing car interior, chain swinging from the lean forward, full body visible seated on car hood, candid street photo",
  porch_post: "POSE: Sitting on the edge of concrete front porch steps of a city rowhouse, elbows on both knees leaning slightly forward, one hand throwing a hand sign at camera held at chest level, other hand holding a fat rubber-banded cash stack dangling between the fingers above the lower step, fitted cap cocked slightly to the side, cold mean mug expression with direct intense stare into lens, iron railing beside, brick facade of house behind, city block visible in distance, full body visible on the steps, raw candid street photo",
  cash_fan_face: "POSE: Holding an enormous fan of loose $100 bills spread wide open directly in front of the lower face, covering everything from the nose bridge down — only the eyes and forehead visible above the massive cash fan, both hands gripping opposite edges of the fanned spread with at least 40-50 bills fanned open, eyes looking just over the top edge of the cash directly into camera with a dead cold stare or slow squint, Benjamin Franklin faces clearly visible across the spread of bills, full upper body visible, candid photo",
  vault_flex: "POSE: Standing directly in front of an open round combination floor safe or wall vault, the safe interior completely packed with neat rows of rubber-banded cash brick stacks overflowing from floor to ceiling inside, both arms extended reaching inside the open safe pulling out bricks — one brick gripped firmly in each hand being pulled toward camera, grinning wide with pure energy, combination lock dial visible on the open safe door swung beside, bricks nearly spilling out, full body visible, candid photo",
  briefcase_open: "POSE: Standing squarely facing camera holding an open silver Halliburton-style aluminum hard-shell briefcase angled 45 degrees toward the lens, the interior completely filled with perfectly packed uniform rows of rubber-banded $100 bill bricks covering every square inch of both sides of the case, one hand gripping the briefcase handle below, other hand holding the lid fully open for display, tilting the open case toward camera to show the entire packed interior, expression of calm satisfaction and complete dominance, full body visible, candid photo",
  money_throne: "POSE: Sitting upright on a makeshift throne constructed from 12-15 rubber-banded cash brick stacks arranged and stacked as a seat — literally sitting on top of the money like a king, additional loose bricks and scattered $100 bills covering the floor all around both feet, both hands resting flat on knees with diamond rings visible, completely upright commanding posture, chin slightly elevated, cold unbothered king expression staring directly into camera, chains resting on chest, full body visible with the cash throne clearly showing beneath, raw candid photo",
  bath_cash: "POSE: Sitting inside a bathtub filled completely to the brim with loose $100 bills — submerged from the waist down in cash, bills overflowing over the edges of the tub and spilling thick onto the bathroom tile floor, both arms draped over the tub edges each holding a rubber-banded cash brick, wide open laughing expression looking directly at camera with complete joy and energy, champagne or Hennessy bottle balanced on the tub edge, marble or tiled bathroom walls visible, full body in tub visible, candid photo",
};

export function getRandomOutfit(): string {
  const outfits = Object.values(OUTFITS);
  return outfits[Math.floor(Math.random() * outfits.length)];
}

export function getRandomScene(): { scene: string; light: string } {
  const scenes = Object.values(SCENES);
  return scenes[Math.floor(Math.random() * scenes.length)];
}

export function getRandomPose(): string {
  const poses = Object.values(POSES);
  return poses[Math.floor(Math.random() * poses.length)];
}

export function getRandomPoses(count: number): string[] {
  const poses = Object.values(POSES);
  const selected: string[] = [];
  for (let i = 0; i < count; i++) {
    selected.push(poses[Math.floor(Math.random() * poses.length)]);
  }
  return selected;
}

export function getRandomPants(): string {
  const pants = Object.values(PANTS);
  return pants[Math.floor(Math.random() * pants.length)];
}

export function getRandomShoes(): string {
  const shoes = Object.values(SHOES);
  return shoes[Math.floor(Math.random() * shoes.length)];
}
